Source = \
	NpdDevelopmentWellbore.java \
	NpdExplorationWellbore.java \
	NpdOtherWellbore.java \
	NpdWellbore.java \
	NpdWellboreReader.java \

Main = NpdWellboreReader

include $(DEV_HOME)/NpdIo/Makefile
